AWSTemplateFormatVersion: "2010-09-09"
Description: ECR template
Resources:
  Repository:
    Type: AWS::ECR::Repository
    Properties:
      LifecyclePolicy:
        LifecyclePolicyText: |
          {
            "rules": [
              {
                "rulePriority": 1,
                "description": "Delete unused images",
                "selection": {
                  "tagStatus": "untagged",
                  "countType": "sinceImagePushed",
                  "countUnit": "days",
                  "countNumber": 1
                },
                "action": {
                  "type": "expire"
                }
              }
            ]
          }
      Tags:
        -
          Key: Name
          Value: !Sub "${AWS::StackName}-Repository"
        -
          Key: CostTag
          Value: !Ref AWS::StackName
